/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/openkruise/kruise/pkg/apis/apps/v1alpha1"
	scheme "github.com/openkruise/kruise/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RolloutDefinitionsGetter has a method to return a RolloutDefinitionInterface.
// A group's client should implement this interface.
type RolloutDefinitionsGetter interface {
	RolloutDefinitions(namespace string) RolloutDefinitionInterface
}

// RolloutDefinitionInterface has methods to work with RolloutDefinition resources.
type RolloutDefinitionInterface interface {
	Create(*v1alpha1.RolloutDefinition) (*v1alpha1.RolloutDefinition, error)
	Update(*v1alpha1.RolloutDefinition) (*v1alpha1.RolloutDefinition, error)
	UpdateStatus(*v1alpha1.RolloutDefinition) (*v1alpha1.RolloutDefinition, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RolloutDefinition, error)
	List(opts v1.ListOptions) (*v1alpha1.RolloutDefinitionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RolloutDefinition, err error)
	RolloutDefinitionExpansion
}

// rolloutDefinitions implements RolloutDefinitionInterface
type rolloutDefinitions struct {
	client rest.Interface
	ns     string
}

// newRolloutDefinitions returns a RolloutDefinitions
func newRolloutDefinitions(c *AppsV1alpha1Client, namespace string) *rolloutDefinitions {
	return &rolloutDefinitions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rolloutDefinition, and returns the corresponding rolloutDefinition object, and an error if there is any.
func (c *rolloutDefinitions) Get(name string, options v1.GetOptions) (result *v1alpha1.RolloutDefinition, err error) {
	result = &v1alpha1.RolloutDefinition{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RolloutDefinitions that match those selectors.
func (c *rolloutDefinitions) List(opts v1.ListOptions) (result *v1alpha1.RolloutDefinitionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RolloutDefinitionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rolloutDefinitions.
func (c *rolloutDefinitions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a rolloutDefinition and creates it.  Returns the server's representation of the rolloutDefinition, and an error, if there is any.
func (c *rolloutDefinitions) Create(rolloutDefinition *v1alpha1.RolloutDefinition) (result *v1alpha1.RolloutDefinition, err error) {
	result = &v1alpha1.RolloutDefinition{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		Body(rolloutDefinition).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rolloutDefinition and updates it. Returns the server's representation of the rolloutDefinition, and an error, if there is any.
func (c *rolloutDefinitions) Update(rolloutDefinition *v1alpha1.RolloutDefinition) (result *v1alpha1.RolloutDefinition, err error) {
	result = &v1alpha1.RolloutDefinition{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		Name(rolloutDefinition.Name).
		Body(rolloutDefinition).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rolloutDefinitions) UpdateStatus(rolloutDefinition *v1alpha1.RolloutDefinition) (result *v1alpha1.RolloutDefinition, err error) {
	result = &v1alpha1.RolloutDefinition{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		Name(rolloutDefinition.Name).
		SubResource("status").
		Body(rolloutDefinition).
		Do().
		Into(result)
	return
}

// Delete takes name of the rolloutDefinition and deletes it. Returns an error if one occurs.
func (c *rolloutDefinitions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rolloutDefinitions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rolloutDefinition.
func (c *rolloutDefinitions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RolloutDefinition, err error) {
	result = &v1alpha1.RolloutDefinition{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rolloutdefinitions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
