/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/hellolijj/kruise/pkg/apis/apps/v1alpha1"
	scheme "github.com/hellolijj/kruise/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RolloutControlsGetter has a method to return a RolloutControlInterface.
// A group's client should implement this interface.
type RolloutControlsGetter interface {
	RolloutControls(namespace string) RolloutControlInterface
}

// RolloutControlInterface has methods to work with RolloutControl resources.
type RolloutControlInterface interface {
	Create(*v1alpha1.RolloutControl) (*v1alpha1.RolloutControl, error)
	Update(*v1alpha1.RolloutControl) (*v1alpha1.RolloutControl, error)
	UpdateStatus(*v1alpha1.RolloutControl) (*v1alpha1.RolloutControl, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RolloutControl, error)
	List(opts v1.ListOptions) (*v1alpha1.RolloutControlList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RolloutControl, err error)
	RolloutControlExpansion
}

// rolloutControls implements RolloutControlInterface
type rolloutControls struct {
	client rest.Interface
	ns     string
}

// newRolloutControls returns a RolloutControls
func newRolloutControls(c *AppsV1alpha1Client, namespace string) *rolloutControls {
	return &rolloutControls{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rolloutControl, and returns the corresponding rolloutControl object, and an error if there is any.
func (c *rolloutControls) Get(name string, options v1.GetOptions) (result *v1alpha1.RolloutControl, err error) {
	result = &v1alpha1.RolloutControl{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RolloutControls that match those selectors.
func (c *rolloutControls) List(opts v1.ListOptions) (result *v1alpha1.RolloutControlList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RolloutControlList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rolloutControls.
func (c *rolloutControls) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a rolloutControl and creates it.  Returns the server's representation of the rolloutControl, and an error, if there is any.
func (c *rolloutControls) Create(rolloutControl *v1alpha1.RolloutControl) (result *v1alpha1.RolloutControl, err error) {
	result = &v1alpha1.RolloutControl{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		Body(rolloutControl).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rolloutControl and updates it. Returns the server's representation of the rolloutControl, and an error, if there is any.
func (c *rolloutControls) Update(rolloutControl *v1alpha1.RolloutControl) (result *v1alpha1.RolloutControl, err error) {
	result = &v1alpha1.RolloutControl{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		Name(rolloutControl.Name).
		Body(rolloutControl).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rolloutControls) UpdateStatus(rolloutControl *v1alpha1.RolloutControl) (result *v1alpha1.RolloutControl, err error) {
	result = &v1alpha1.RolloutControl{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		Name(rolloutControl.Name).
		SubResource("status").
		Body(rolloutControl).
		Do().
		Into(result)
	return
}

// Delete takes name of the rolloutControl and deletes it. Returns an error if one occurs.
func (c *rolloutControls) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rolloutControls) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rolloutcontrols").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rolloutControl.
func (c *rolloutControls) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RolloutControl, err error) {
	result = &v1alpha1.RolloutControl{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rolloutcontrols").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
