name: "Create cluster using KinD"
on: push

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.1.0
    - name: setup-k8s
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        echo $KUBECONFIG
        kubectl cluster-info
        kubectl get pods -n kube-system
    - name: pwd
      run: |
        pwd
        ls
        go env | grep GOPATH
        mkdir -p ~/go/src/github.com/openkruise/kruise
        cp -r ./ ~/go/src/github.com/openkruise/kruise
        cd ~/go/src/github.com/openkruise/kruise
    - name: e2e-test
      run: |
        go env | grep GOPATH
        go test ./test/e2e/ -v -args "-kubeconfig=/home/runner/work/kruise/kruise"